### ISSUE TITLE
better coding

### ISSUE THREAD

**Issue by JericoFX** [Leap0p0/popo_rich_presence#1]
Hi, nice to see you´r scripts, here is some tips,
use PlayerPedId() instead GetPlayerPed(-1) you dont need to add Citizen. to CreateThread() and Wait().

if you want to learn more i recomend this 
https://manason.github.io/effective-fivem-lua/

**Comment by Leap0p0** [comment]
Hi @JericoFX !
First of all, thank you for your message and the interest in this script! ^^

I'm changing that right away (Shame on me, I didn't change it)!

**Comment by Leap0p0** [comment]
It's done @JericoFX ! 
Thanks again !

**Comment by JericoFX** [comment]
not problem my friend! living and learning
